steps:

- id: 'Install app'
  name: 'gcr.io/cloud-builders/go'
  args: ['install', 'sum']
  env: ['GOPATH=.']

- id: 'Test app'
  name: 'gcr.io/cloud-builders/go'
  args: ['test', '-v','./...']
  env: ['GOPATH=.']

- id: 'Build image'
  name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/$PROJECT_ID/app', '.']

images: ['gcr.io/$PROJECT_ID/app']